// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgfbgohcayhyuwcyxzcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZmJnb2hjYXloeXV3Y3l4emNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDUxMDcsImV4cCI6MjA2OTI4MTEwN30.HRzmS39z-rVCtPnfMq9x3O5PsNXH0piM1s_xhw-r0lM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});